# Generated by Django 3.0.5 on 2020-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpet',
            name='pet_type',
            field=models.CharField(max_length=20),
        ),
    ]
