# Generated by Django 3.0.5 on 2020-04-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={},
        ),
    ]
