# Generated by Django 3.0.5 on 2020-04-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200416_1536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertoken',
            table=None,
        ),
    ]
