# Generated by Django 3.0.5 on 2020-04-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200416_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='t_user_token',
        ),
    ]
